services:
    db:
        image: mysql:5.7
        volumes:
            - db_data:var/lib/mysql
        container_name: "db"
        restart: always
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_NAME}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"

    todo-back:
        image: "todo-back"
        restart: "on-failure"
        build:
            context: .
        ports:
            - "5858:5858"
        container_name: "todo-back"
        depends_on:
            - db
version: "3.7"
