version: "3.7"
services:
    db:
        image: mysql:5.7
        container_name: db
        restart: always
        ports:
            - "3307:3306"
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
        environment:
            MYSQL_ROOT_PASSWORD: todoback
            MYSQL_DATABASE: todoDB
            MYSQL_USER: todo
            MYSQL_PASSWORD: todoback
        volumes:
            - ../db_data:/var/lib/mysql
        networks:
            - app-network

    todo-back:
        image: "todo-back"
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: "on-failure"
        ports:
            - "5858:5858"
        container_name: "todo-back"
        depends_on:
            - db
        networks:
            - app-network
networks:
    app-network:
        driver: bridge